apiVersion: v1
kind: Secret
metadata:
  name: secret-llm
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
  annotations:
    controller.devfile.io/mount-as: env
    {{- include "devspaces-instance.argocd-syncwave" . | nindent 4 }}
type: Opaque
data:
  LLM_API_KEY: {{ .Values.litemaas.apiKey | b64enc | quote }}
  LLM_BASE_URL: {{ .Values.litemaas.apiUrl | b64enc | quote }}
  LLM_MODEL: {{ .Values.litemaas.model | b64enc | quote }}

  
