apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" .Values.devspaces.name "namespace" .Values.argocd.namespace "syncWave" "0") }}
spec:
  destination:
    namespace: {{ .Values.devspaces.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/devspaces
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    helm:
      valuesObject:
        devspaces-instance:
          litemaas:
            apiKey: {{ .Values.litemaas.apiKey }}
            apiUrl: {{ .Values.litemaas.apiUrl }}
            model: {{ .Values.litemaas.model }}
          openVSXURL: https://open-vsx-server-{{ .Values.openvsx.namespace }}.{{ .Values.deployer.domain }}
{{ include "app-of-apps.syncPolicy" . | indent 2 }}
